### ISSUE TITLE
Pre work event

### ISSUE THREAD

**Issue by orolyn** [mmoreram/GearmanBundle#120]
It would be nice to have events before each job is run, however Gearman doesn't provide a simple way of doing this.

I have tested a simple solution where an intermediate method is called which then forwards the jobs to the worker class.

https://gist.github.com/orolin/b4dfb9bd247ecb49d31a

This is a segment of the GearmanExecute class with an added method `doRunJob`.
Instead of assigning the worker class mehods, all jobs are routed to this method, which in turn forwards the request to the worker class.

What do you reckon?  It may be a bit untidy, but I'd like to see this functionality in there somehow.

**Comment by skylord123** [comment]
Isn't there an event for this now? Can this old issue be closed?

**Comment by daum** [comment]
There is the Starting Work event which I believe is going to do what the original request is here.  However to restart the PDO you'd want it inside your worker so you could just put it at the top of the function itself.

Going to close this as there is a starting work event now.
