### ISSUE TITLE
Queue Length Not Increasing

### ISSUE THREAD

**Issue by clafouti2104** [mmoreram/GearmanBundle#130]
Hello,

I got a problem with my workers.
3 workers are running but only one is working.
Where I monitor gearman over telnet, I see that the queue length is always at 1. 
root@XXXX:/var/www/domantic# telnet localhost 4730
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
status
DomanticCommunicationBundleControllerScenarioController~executeScenario 0   0   1
DomanticCommunicationBundleControllerCommunicationController~addTask    1   0   0
.
status
DomanticCommunicationBundleControllerScenarioController~executeScenario 0   0   1
DomanticCommunicationBundleControllerCommunicationController~addTask    1   0   0
.

ERR UNKNOWN_COMMAND Unknown+server+command

ERR UNKNOWN_COMMAND Unknown+server+command
status
DomanticCommunicationBundleControllerScenarioController~executeScenario 0   0   1
DomanticCommunicationBundleControllerCommunicationController~addTask    1   1   2 

When I'm request a job to be done, the queue length isn't increasing... 
$this->gearman->doHighBackgroundJob('DomanticCommunicationBundleControllerCommunicationController~addTask', 'value1');
Can you help me?
Thank you a lot

**Comment by daum** [comment]
If you need help please post a an example of working code and how to replicate.
