### ISSUE TITLE
supervisor fail on daemonizing failed since v3.0.0

### ISSUE THREAD

**Issue by AliHichem** [mmoreram/GearmanBundle#141]
Hi,

Since v3.0.0 the worker still work well on CLI but fail to be deamonized with supervisor. I had to rollback to V2.4.* to have it working again with supervisor. My Supervisor logger says:
```
2015-03-10 00:03:02,765 INFO daemonizing the supervisord process
2015-03-10 00:03:02,765 INFO supervisord started with pid 12575
2015-03-10 00:03:03,769 INFO spawned: 'worker_mailer_0' with pid 12582
2015-03-10 00:03:03,943 INFO exited: worker_mailer_0 (exit status 0; not expected)
2015-03-10 00:03:04,947 INFO spawned: 'worker_mailer_0' with pid 12584
2015-03-10 00:03:05,130 INFO exited: worker_mailer_0 (exit status 0; not expected)
2015-03-10 00:03:07,135 INFO spawned: 'worker_mailer_0' with pid 12588
2015-03-10 00:03:07,319 INFO exited: worker_mailer_0 (exit status 0; not expected)
2015-03-10 00:03:10,325 INFO spawned: 'worker_mailer_0' with pid 12590
2015-03-10 00:03:10,499 INFO exited: worker_mailer_0 (exit status 0; not expected)
2015-03-10 00:03:11,501 INFO gave up: worker_mailer_0 entered FATAL state, too many start retries too quickly
```
I'm not sure where is the problem but it look like it have a bad exit code coming from the worker that make supervisor "think" the worker is done running .. 

Thank you !

**Comment by dav-m85** [comment]
Well, it looks like your process is exiting right away, I don't think supervisor is to blame. Can you provide some code to reproduce your issue ?

**Comment by AliHichem** [comment]
Actually my same code works like a charm with the version 2.4. As soon as I switch to the version 3 I get this problem ..
About the code I don't know which part should I give you so here's the code of one of my workers :
```
/**
 * @Gearman\Work(
 *      iterations = 1,
 *      description="Mail tools", 
 *      defaultMethod="doLow",
 *      service="gearman.worker.mail"
 * ) 
 */
class MailWorker extends Worker
{

    /**
     * send mail
     * 
     * @Gearman\Job(iterations=1, name="mail_send", description="send mail", defaultMethod="doLow")
     *
     * @param \GearmanJob $job Object with job parameters
     *
     * @return boolean
     */
    public function send(\GearmanJob $job)
    {
        $_params    = json_decode($job->workload());
        $mail_id    = $_params->mail_id;
        $dm         = $this->_container->get('doctrine.odm.mongodb.document_manager');
        $t          = $this->_container->get('swiftmailer.transport.real');
        $mail_queue = $dm->find('MailerBundle:MailQueue', $mail_id);
        /* @var $swift_obj \Swift_Message */
        $swift_obj  = unserialize($mail_queue->getRaw());
        $message    = $swift_obj;
        $this->logger->info(sprintf("Sending mail from=%s to=%s subject=%s", json_encode($mail_queue->getFrom()), json_encode($mail_queue->getTo()), $mail_queue->getSubject()));
        if (!$t->isStarted())
        {
            $t->start();
        }
        $s = $t->send($message);
        if ($s > 0)
        {
            $mail_queue->setStatus('sent');
        }
        else
        {
            $mail_queue->setStatus('failed');
        }
        $mail_queue->setSent(new \DateTime);
        $dm->flush();
        $t->stop();
    }

}
```

**Comment by dav-m85** [comment]
Sorry for late reply. Weird as for the "working with 2.4" part. Supervisor is not meant to relaunch all the time a task. It is meant to keep long running deamons... running.

Your code here, especially ```@Gearman\Job(iterations=1, name="mail_send", description="send mail", defaultMethod="doLow")``` reads "execute the worker with one payload and stop" runs too quickly.

I'd suggest, depending on your setup, to set an iterations to 100 (sending 100 emails before restarting the worker by supervisor). You'll surely have better results.

**Comment by AliHichem** [comment]
You have a god point here, it might run too fast ! But yet again I'm a little suspicious because with right exit code all of this wouldn't happen: As you can see the error message is "worker_mailer_0 (exit status 0; not expected)" so something is not right with the exist status code. 

I agree that having one iteration per job might not be adequate but I did it on purpose and I don't see why gearman or supervisor would reject that. It's working great with the version 2 and I've been working with for long time with serious project, I think I'm gonna just stick with that version for now ( I don't really have time to make deep debug , this is why I contacted you :) ).

Thank you anyway, I appreciate your help !
(You can close this bug if you want)
