### ISSUE TITLE
worker/job not executing correctly

### ISSUE THREAD

**Issue by Rid** [mmoreram/GearmanBundle#143]
I am trying to get the example from the wiki working, but have failed so far.

I have:
GearmanBundle dev-master
gearman php extension version 1.1.2
libgearman version 1.0.6
PHP 5.6.4-4ubuntu2 (cli) (built: Mar  3 2015 14:58:55)

Gearmand is running:

```
# gearadmin --server-version
1.0.6

gearmand  5858  gearman   10u  IPv4 192461      0t0  TCP 127.0.0.1:4730 (LISTEN)
```

My workers and jobs are exactly the same as the wiki, but when I try to execute a worker or job it outputs the description to the console and then exits immediately:

```
[10:49:33 root@dev-demo gui ]# php app/console gearman:worker:execute CyloAppBundleUtilsJobManager --no-interaction
[2015-03-17 10:51:19] loading...

@Worker\className : Cylo\AppBundle\Utils\JobManager
@Worker\fileName : /mnt/hgfs/cyloui/gui/src/Cylo/AppBundle/Utils/JobManager.php
@Worker\nameSpace : Cylo\AppBundle\Utils
@Worker\callableName: CyloAppBundleUtilsJobManager
@Worker\supervisord : /usr/bin/php /mnt/hgfs/cyloui/gui/app/console gearman:worker:execute CyloAppBundleUtilsJobManager --no-interaction
@Worker\service : jobmanager
@worker\iterations : 150
@Worker\#jobs : 1
@Worker\jobs

    # CyloAppBundleUtilsJobManager~testA

@worker\servers :

    #localhost - 127.0.0.1:4730

@Worker\description :

    No description is defined

[2015-03-17 10:51:19] loaded. Ctrl+C to break
[10:51:19 root@dev-demo gui ]#
```

Strace shows the connection to the server seems to be closed immediately:

```
write(5, "\33[32m[2015-03-17 10:51:47] loaded. Ctrl+C to break\33[39m\n", 56[2015-03-17 10:51:47] loaded. Ctrl+C to break
) = 56
pipe2([8, 9], O_NONBLOCK|O_CLOEXEC)     = 0
socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_TCP) = 10
setsockopt(10, SOL_TCP, TCP_NODELAY, [1], 4) = 0
setsockopt(10, SOL_SOCKET, SO_LINGER, {onoff=1, linger=10}, 8) = 0
setsockopt(10, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
setsockopt(10, SOL_SOCKET, SO_SNDBUF, [32768], 4) = 0
setsockopt(10, SOL_SOCKET, SO_RCVBUF, [32768], 4) = 0
connect(10, {sa_family=AF_INET, sin_port=htons(4730), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
close(8)                                = 0
close(9)                                = 0
shutdown(10, SHUT_RDWR)                 = 0
close(10)                               = 0
access("/mnt/hgfs/cyloui/gui/vendor/symfony/symfony/src/Symfony/Component/Console/Event/ConsoleTerminateEvent.php", F_OK) = 0
lstat("/mnt/hgfs/cyloui/gui/vendor/symfony/symfony/src/Symfony/Component/Console/Event/ConsoleTerminateEvent.php", {st_mode=S_IFREG|0644, st_size=1306, ...}) = 0
lstat("/mnt/hgfs/cyloui/gui/vendor/symfony/symfony/src/Symfony/Component/Console/Event", {st_mode=S_IFDIR|0755, st_size=204, ...}) = 0
open("/mnt/hgfs/cyloui/gui/vendor/symfony/symfony/src/Symfony/Component/Console/Event/ConsoleTerminateEvent.php", O_RDONLY) = 8
```

The gearman logs are empty and there's no errors/exceptions coming from php.

**Comment by Rid** [comment]
I switched to the latest stable version (3.0.1) and it's working fine:

    write(5, "\33[32m[2015-03-17 11:35:12] loaded. Ctrl+C to break\33[39m\n", 56[2015-03-17 11:35:12] loaded. Ctrl+C to break
    ) = 56
    pipe2([8, 9], O_NONBLOCK|O_CLOEXEC)     = 0
    socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_TCP) = 10
    setsockopt(10, SOL_TCP, TCP_NODELAY, [1], 4) = 0
    setsockopt(10, SOL_SOCKET, SO_LINGER, {onoff=1, linger=10}, 8) = 0
    setsockopt(10, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
    setsockopt(10, SOL_SOCKET, SO_SNDBUF, [32768], 4) = 0
    setsockopt(10, SOL_SOCKET, SO_RCVBUF, [32768], 4) = 0
    connect(10, {sa_family=AF_INET, sin_port=htons(4730), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
    poll([{fd=10, events=POLLOUT}, {fd=8, events=POLLIN}], 2, 4294967295) = 1 ([{fd=10, revents=POLLOUT}])
    sendto(10, "\0REQ\0\0\0\32\0\0\0\nexceptions", 22, MSG_NOSIGNAL, NULL, 0) = 22
    recvfrom(10, 0x2dc3fc1, 8192, 16384, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
    poll([{fd=10, events=POLLIN}, {fd=8, events=POLLIN}], 2, 4294967295) = 1 ([{fd=10, revents=POLLIN}])
    recvfrom(10, "\0RES\0\0\0\33\0\0\0\nexceptions", 8192, MSG_NOSIGNAL, NULL, NULL) = 22
    sendto(10, "\0REQ\0\0\0\1\0\0\0\"CyloAppBundleUtilsJobManager~testA", 46, MSG_NOSIGNAL, NULL, 0) = 46
    sendto(10, "\0REQ\0\0\0'\0\0\0\0", 12, MSG_NOSIGNAL, NULL, 0) = 12
    recvfrom(10, 0x2dc3fc1, 8192, 16384, 0, 0) = -1 EAGAIN (Resource temporarily unavailable)
    poll([{fd=10, events=POLLIN}, {fd=8, events=POLLIN}], 2, 4294967295) = 1 ([{fd=10, revents=POLLIN}])
    recvfrom(10, "\0RES\0\0\0\n\0\0\0\0", 8192, MSG_NOSIGNAL, NULL, NULL) = 12
    sendto(10, "\0REQ\0\0\0\4\0\0\0\0", 12, MSG_NOSIGNAL, NULL, 0) = 12
    poll([{fd=10, events=POLLIN}, {fd=8, events=POLLIN}], 2, 4294967295
    
The worker is registered:

    # gearadmin --status
    CyloAppBundleUtilsJobManager~testA	0	0	2

**Comment by dominch** [comment]
Got same issue with latest dev version, rolling back to stable fixed problem.
