### ISSUE TITLE
Worker outside current project

### ISSUE THREAD

**Issue by JordyMoos** [mmoreram/GearmanBundle#145]
Hi,

Is there a way to consume job outside the current symfony2 project.

So for example i have 1 server running symfony2 creating all these jobs that should be done eventually. And a set of working servers maybe not even running symfony2.

If i now call "doBackgroundJob" it expects me to have a worker for the job already. But the only thing i want is that the job gets queued in gearman and some other service will receive the job (because he singed up as a worker) and do its work. So i do not want to define the worker in this symfony2 project.

Is that possible or is that not where this bundle is created for?

Cheers

**Comment by daum** [comment]
Yes you can just setup a worker to listen for the specific job name.  You would need to create an annotation inside the project for the job so the bundle does not throw an error stating non-existing job when you call it.  You do not need to actually run the job inside the project though.
