### ISSUE TITLE
worker list not working

### ISSUE THREAD

**Issue by Perfect-Web** [mmoreram/GearmanBundle#148]
PHP Fatal error:  Call to a member function getWorkers() on null in  .../vendor/mmoreram/gearman-bundle/Mmoreram/GearmanBundle/Command/GearmanWorkerListCommand.php on line 78

**Comment by nahuelsgk** [comment]
Same here. Any idea. Checking the line 78:

$workers = $this->gearmanClient->getWorkers(); And I feel like the client is no set. Why?

**Comment by rajasaur** [comment]
The Command when run doesnt go through the same flow as the service and GearmanWorkerListCommand which expects the GearmanClient as a DI never gets set. Im having the same issue and am on Symfony 2.3, Maybe things have changed in a later release?

**Comment by rajasaur** [comment]
Figured it out after head-banging for a few hours. The packagist.org said Version 3.0.x of gearmanbundle was supported for symfony 2.4 and above (And 3.0.0 dint have a required for frameworkbundle , I assumed that it supported symfony fraemwork bundle 2.2 and above).

If you use the gearman-bundle 2.x-dev or 2.4.2, it works with symfony-framework 2.2 and above and none of these reported problems exist. Try using a lower version of it or upgrade the framework to 2.4 and above.

**Comment by Pharkie** [comment]
Thanks @rajasaur that was clear and worked for me. I did the latter, upgrading to 2.4 (use 2.4.10) and everything seems still to work on the app, plus the error from Gearman about workers and null has gone.
