### ISSUE TITLE
Job iterations vs worker iterations

### ISSUE THREAD

**Issue by daum** [mmoreram/GearmanBundle#150]
It appears that the job specific iterations don't have any actual affect on anything.  I have 10 jobs for example in one worker, the default is 10 iterations, but one of the jobs has iterations=1. 

However, when I run it to execute all jobs it only takes the default iterations.  When you run a specific job it works fine, and gets the correct iterations.  

This should be taking both into account regardless of how it is run no?  So it looks like you'd need to look up the iterations per job versus just passing through one variable to runJob which is iterations.  You'd then track the iterations per job, decreasing each counter as necessary.  

So question would be is this intended to only do the iterations on a job basis if you run a specific job vs the worker?  I could see that is the intended way, if so it should be documented.

**Comment by bmeynell** [comment]
Were these questions answered and/or added to the documentation?

**Comment by mmoreram** [comment]
@bmeynell nice to see you here!

@daum is working on that :)

**Comment by daum** [comment]
@bmeynell @mmoreram I actually closed it out since noone else seemed to have the question.  

If this is something more people would be interested in then we could look to adding it in.
