### ISSUE TITLE
Ready for Symfony 3 and/or PHP 7

### ISSUE THREAD

**Issue by distantbit** [mmoreram/GearmanBundle#160]
I was wondering if there will be support for Symfony 3. When I try to upgrade the GeamanBundle says it needs the symfony/options-resolver in version 2.1 which is bundled in Symfony 2.\* 

When will it be possible to use your bundle with Symfony 3. By the way is your bundle compatible with PHP 7?

**Comment by mmoreram** [comment]
Yes, absolutely.
Do you want to take care about it?
Otherwise I will take a look myself and we will update it ASAP.

Thanks :)

**Comment by skylord123** [comment]
Looking forward to Symfony 3.0 support. Didn't know this bundle wasn't updated yet. I should have checked.

Oh well. Any timeline when it will be ready? Even for testing?

**Comment by mmoreram** [comment]
@skylord123 Sure :)

https://github.com/mmoreram/GearmanBundle/issues/162

Feel free to make a PR with the update and a call for all the community for testing it :)

Thanks!

**Comment by gepo** [comment]
PR  #166 is about Symfony 3.0 compatiblity

**Comment by Grimbode** [comment]
@gepo how is the symfony3 compatibility coming along?

**Comment by gepo** [comment]
@Grimbode PR is waiting to be accepted. You can use my branch https://github.com/gepo/GearmanBundle/tree/symfony30 if you want.

**Comment by daum** [comment]
Going to close the bundle is compatible since tag v4.0.0
