### ISSUE TITLE
Symfony2 Mmoreram GearmanClient fails to load

### ISSUE THREAD

**Issue by marcosrachid** [mmoreram/GearmanBundle#167]
Hello Mmoreram,

I'm facing some problems with the GearmanBundle, since after the process of installation succeeded, I can find all my jobs and workers:

> $ app/console gearman:worker:list
> @Worker:
> HeloBundle\Workers\PushWorker
> callablename:  HeloBundleWorkersPushWorker
> Jobs:
>   - #1
>       name: sendPushJob
>       callablename: HeloBundleWorkersPushWorker~sendPushJob
> 
> @Worker:  HeloBundle\Workers\EmailWorker
> callablename:  HeloBundleWorkersEmailWorker
> Jobs:
>   - #2
>       name: sendMailJob
>       callablename: HeloBundleWorkersEmailWorker~sendMailJob

As you can se, my gearman is installed on php:

> $ php -i | grep gearman | grep enabled
> gearman support => enabled

But when I call this:

```
try
 {
                $gearman = $this->container->get('gearman');
                $gearman->doBackgroundJob('HeloBundleWorkersPushWorker~sendPushJob', json_encode(array(
                        'tags' => $tags,
                        'message' => $message,
                        'all' => $all
                    )));
                $flash['type'] = 'notice';
                $flash['message'] = 'Success.';
            } catch (\Exception $e) {
                $flash['type'] = 'warning';
                $flash['message'] = 'Error.';
            }
```

It returns me this message:

> request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "GearmanClient" from the global namespace. Did you forget a "use" statement for "Mmoreram\GearmanBundle\Service\GearmanClient"?" at /var/www/stage/vendor/mmoreram/gearman-bundle/Mmoreram/GearmanBundle/Service/GearmanClient.php line 90 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"GearmanClient\" from the global namespace.\nDid you forget a \"use\" statement for \"Mmoreram\\GearmanBundle\\Service\\GearmanClient\"? at /var/www/stage/vendor/mmoreram/gearman-bundle/Mmoreram/GearmanBundle/Service/GearmanClient.php:90)"} []

The bundle can't load the native GearmanClient() on global scope. Can you help me with this ?

**Comment by daum** [comment]
I think you need to install and enable the php gearman extension. That's the error you are seeing.

**Comment by marcosrachid** [comment]
The Extension is already installed

gearman

gearman support	enabled
extension version	1.1.2
libgearman version	1.0.6
Default TCP Host	localhost
Default TCP Port	4730

**Comment by daum** [comment]
You sure it's loaded in whatever environment you are getting the error in? Ie on CLI php -I|grep gearman. Or phpinfo in your browser ?  It's saying it can't find it, that class is part of that module.

**Comment by marcosrachid** [comment]
I'm getting this from both "php -i" and browser.

Actually, I already tested in a external file and it instantiates the native GearmanClient normally, but on the Mmoreram GearmanBundle It is returning this error.

Could it be the apxs2 ?

**Comment by daum** [comment]
Not sure then on that one then.  If you can run a sample PHP app via the same environment, ie 
`$gearman = new \GearmanClient();` and it doesn't error then I'm stumped.

**Comment by bmeynell** [comment]
The bundle has a class named GearmanClient. Did you define a DIC parameter
that extends or overrides that class?

Not sure then on that one then. If you can run a sample PHP app via the
same environment, ie
$gearman = new \GearmanClient(); and it doesn't error then I'm stumped.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/mmoreram/GearmanBundle/issues/167#issuecomment-200784672>

**Comment by marcosrachid** [comment]
I found it.

It seems the apache was pointing to a different conf.d.

Thank you guys for the help
