### ISSUE TITLE
Segmentation fault in 3.0.2

### ISSUE THREAD

**Issue by er1z** [mmoreram/GearmanBundle#169]
PHP 7.0.8, Ubuntu Linux, Gearman & pecl-gearman compiled from scratch - 1.1.12.

When I upgraded this bundle to 3.0.2, my workers start to crash with "segmentation fault". I've gone deeper - when I rollback to commit before 261b10a413074fc770aedbc60365e6aad652c550, everyhing went back.

Does anyone else experience a simillar issue?

**Comment by daum** [comment]
This is fixed from PR https://github.com/mmoreram/GearmanBundle/pull/175

**Comment by eloirobe** [comment]
Can you update the release 3.0.2 for users that have symfony 2+ ? 

Thanks

**Comment by daum** [comment]
@eloirobe I'll try to take a look at getting that pulled into that set of releases hopefully later this week.  If you have time to make a PR, it should be a fairly easy cherry pick from: https://github.com/mmoreram/GearmanBundle/commit/a69e4707b843cc6dc79c99c7510ee5c83a151e20

**Comment by daum** [comment]
@eloirobe should be all set in https://github.com/mmoreram/GearmanBundle/releases/tag/v3.0.3
