### ISSUE TITLE
Symfony3.3 removed deprecation error [Invalid key "kernel" found in arguments of method "__construct()" for service "gearman.parser"]

### ISSUE THREAD

**Issue by AliHichem** [mmoreram/GearmanBundle#178]
Hi ,

This bundle is fantastic so thank you guys.
I'm having this tiny issue when upgrading to symfony 3.3 and I'd like to note that I'm not having this issue with SF 3.2 because the deprecations wasn't removed until SF 3.3. The message I'm getting is : 

>Invalid key "kernel" found in arguments of method "__construct()" for service "gearman.parser"

Any chance we can get a fix for this ?

Thanks

**Comment by daum** [comment]
I'll try to look at this on Friday, if you want to open a PR with the fix before then I can try to get that merged.

**Comment by daum** [comment]
This is now fixed in master and I just published the release "v4.0.3" which has the update in it.

**Comment by AliHichem** [comment]
This is excellent, thank you @daum  !
