### ISSUE TITLE
Use PSR6 instead of doctrine cache

### ISSUE THREAD

**Issue by Nyholm** [mmoreram/GearmanBundle#186]
Have this been discussed before? It would run better with Symfony 3.2+.

**Comment by daum** [comment]
I don't think it has.  We could look into using that so that we don't require the additional dependency of the Doctrine cache.  Would you be thinking of using the Symfony cache component or something else?

**Comment by Nyholm** [comment]
The idea is to remove the doctrine cache dependency and use something that implement PSR6. Like the Symfony Cache component or PHP-cache. 
Using a PSR will give the user control and we are more interoperable.

**Comment by daum** [comment]
Sounds good to me!

**Comment by ro0NL** [comment]
As per https://github.com/doctrine/DoctrineBundle/blob/master/UPGRADE-2.0.md

DoctrineCacheBundle is now deprecated :) ping @daum i think this dependency blocks updating to doctrine-bundle 2.0

**Comment by daum** [comment]
@ro0NL Ah thanks for the heads up, any chance you want to take a crack at it first?
