### ISSUE TITLE
Symfony 5 support ?

### ISSUE THREAD

**Issue by GothShoot** [mmoreram/GearmanBundle#197]
Hi, you have planned a Symfony 5 support ?

**Comment by daum** [comment]
I haven't yet started trying to implement it, but it shouldn't be hard to make it Symfony5 compatible, I can try to look in the coming weeks or if you'd like to try and make a PR that'd be awesome.

**Comment by GothShoot** [comment]
I can try to implement in a Symfony 5 app with littles updates for seeing problems and trying to fix them.

**Comment by daum** [comment]
It may be as simple as updating the composer file to allow 5.0 too.

**Comment by GothShoot** [comment]
@daum I have opened a PR ( #198 ).
PR not covered by pipeline?

**Comment by daum** [comment]
Thanks it should be, travis is showing it up and offering for me to cancel the build but it hasn't kicked in yet... https://travis-ci.org/github/mmoreram/GearmanBundle/builds/752421928

Also mind bumping the travis php versions to include 7.4

**Comment by GothShoot** [comment]
I try to support Symfony 5 in PR :+1:

**Comment by GothShoot** [comment]
Think to migrate on travis-ci.com for open source (see the site travis-ci.org)

**Comment by GothShoot** [comment]
@daum Why phpunit is in low version ?

**Comment by daum** [comment]
Don't have a specific reason since I started helping maintain this budne

**Comment by daum** [comment]
Also looking at it, I think the cache component of the plugin will need to be updated as the cache bundle is abandoned and won't work with Symfony 5, so would need to work on updating the configuration/docs for how to configure that if we were to continue using the doctrine cache.

**Comment by mihaileu** [comment]
Currently we are planning an application migration to sy5 and we are blocked by this package.  How can we help ?

**Comment by daum** [comment]
@mihaileu if you want to work on a PR for Symfony5 support that'd be awesome!

**Comment by GothShoot** [comment]
@mihaileu See #198

**Comment by mihaileu** [comment]
Feel free to test until we launch a stable version, keep in mind that is possible to launch some breaking changes.

**Comment by daum** [comment]
Will try to get some time, we should also make sure to write up a change log/migration guide for the BC updates.

**Comment by mihaileu** [comment]
5.0.0 tag was released
